---
- name: Create Consul service definition
  include_role: name=infra-role-consul-service
  vars:
    consul_config_name:                      '{{ mev_boost_consul_service_file_name }}'
    consul_default_check_disabled:           '{{ mev_boost_consul_check_disabled }}'
    consul_default_check_interval:           '{{ mev_boost_consul_check_interval }}'
    consul_default_check_timeout:            '{{ mev_boost_consul_check_timeout }}'
    consul_default_success_before_passing:   '{{ mev_boost_consul_success_before_passing }}'
    consul_default_failures_before_warning:  '{{ mev_boost_consul_failures_before_warning }}'
    consul_default_failures_before_critical: '{{ mev_boost_consul_failures_before_critical }}'
    consul_services:
      - id:   '{{ mev_boost_service_name }}'
        name: '{{ mev_boost_consul_service_name }}'
        port: '{{ mev_boost_cont_port }}'
        tags: ['{{ env }}.{{ stage }}', 'mev-boost']
        checks:
          - id:   '{{ mev_boost_service_name }}-health'
            type: 'http'
            http: 'http://localhost:{{ mev_boost_cont_port }}'
            # TODO: Use '/eth/v1/builder/status'
